// AUTO-GENERATED by scripts/optimize-gallery.mjs — do not edit by hand.
// Run `npm run optimize:gallery` after adding/removing photos in gallery-originals/.

export type GalleryImage = {
  src: string;
  thumb: string;
  width: number;
  height: number;
  caption?: string;
};

export type GallerySection = { id: string; label: string; images: GalleryImage[] };

export const CONFERENCE_GALLERY: GallerySection[] = [
  {
    "id": "pre-conference",
    "label": "Pre-Conference",
    "images": [
      {
        "src": "/images/galleries/conference/pre-conference/02.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/02.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/03.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/03.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/04.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/04.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/05.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/05.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/06.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/06.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/07.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/07.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/08.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/08.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/09.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/09.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/10.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/10.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/11.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/11.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/12.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/12.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/13.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/13.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/14.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/14.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/15.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/15.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/pre-conference/16.webp",
        "thumb": "/images/galleries/conference/pre-conference/thumbs/16.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      }
    ]
  },
  {
    "id": "day-1",
    "label": "Day 1",
    "images": [
      {
        "src": "/images/galleries/conference/day-1/01.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/01.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/02.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/02.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/03.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/03.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/04.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/04.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/05.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/05.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/07.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/07.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/10.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/10.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/11.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/11.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/12.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/12.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/13.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/13.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/16.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/16.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/17.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/17.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/18.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/18.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/19.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/19.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/20.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/20.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/21.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/21.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/22.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/22.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/23.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/23.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/24.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/24.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/25.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/25.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/26.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/26.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/27.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/27.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/28.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/28.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/29.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/29.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/30.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/30.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/31.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/31.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/32.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/32.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/33.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/33.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/34.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/34.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/35.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/35.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-1/37.webp",
        "thumb": "/images/galleries/conference/day-1/thumbs/37.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      }
    ]
  },
  {
    "id": "day-2",
    "label": "Day 2",
    "images": [
      {
        "src": "/images/galleries/conference/day-2/01.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/01.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/02.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/02.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/03.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/03.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/04.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/04.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/05.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/05.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/06.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/06.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/07.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/07.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/08.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/08.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/09.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/09.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/10.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/10.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/11.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/11.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/12.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/12.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/13.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/13.webp",
        "width": 1365,
        "height": 2048,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/14.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/14.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/15.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/15.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/16.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/16.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/17.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/17.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/18.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/18.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/19.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/19.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/20.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/20.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/21.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/21.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/22.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/22.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/23.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/23.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/24.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/24.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/25.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/25.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/26.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/26.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/27.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/27.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/28.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/28.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/29.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/29.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/30.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/30.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/31.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/31.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      },
      {
        "src": "/images/galleries/conference/day-2/32.webp",
        "thumb": "/images/galleries/conference/day-2/thumbs/32.webp",
        "width": 2048,
        "height": 1365,
        "caption": ""
      }
    ]
  }
];
